[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 10
